### PR TITLE
Added support for multiple parallel animations

### LINKED ISSUE #5: How would you run two tweens at the same time?
Animating a single prop is easy-peasy. But how would you approach animating two integers at the same time? Let's say scrollTop & scrollLeft.

I was thinking about putting in an object of integers into Tweezer.js. That would be the easiest option, but requires an update in the module. Or I could (in my own code) tween from 1 to lets say 100, and calculate my own intermediate values. But that feels weird, and would require me to keep state about the initial & target values. What do you say?

### PR DESCRIPTION
**Pull request by jonahbron**
This PR moves the tweening behavior out into a separate object that can be passed into the config.  By default setting `start` and `end` in the config instantiates the `SingleTweener`.  This is to ensure this change is entirely backwards compatible.  Alternatively, a `MultiTweener` can be passed in to the `tweener` property to allow tweening multiple values simultaneously.  Easing still behaves as normal regardless of the choice of tweener.

Most importantly, this new behavior resides in a separate file that must be explicitly imported by the application, ensuring it's only included if used.

Closes #5

### CODE REVIEW

**Comment by jonahbron** [comment]
Resolves #5

**Comment by jonahbron** [comment]
Closes #5

**Comment by guidobouman** [comment]
Nice PR!

I see you added a different import to keep the impact on the base lib as minimal as possible, sweet! Aren't there only two use cases for Tweezer? A single value & multiple values. Or can you think of another use case? Because if there's only two options, then fanning of the multiple values Tweener in a different import might only cause mental overhead.

@jaxgeller What do you think?

**Comment by jonahbron** [comment]
@guidobouman Yes, I kept it separate to make increase the likelihood that the maintainer would approve based on minimal code size change.  The intent of the library is to be small.

I could imagine more complicated tweeners that could for example tween from one polygon to another, or animate other types of complex structures.

At the very least, it would be nice to merge this "tweener" entity, then I would make another NPM package that contains the multi-tweener.  But this seems like a common enough use-case to merit including in the core.

**Comment by jonahbron** [comment]
@jaxgeller Is there any chance of getting this merged?  Right now my project depends on my fork.  If you don't think this will be merged in any form, I'll probably fork and make my own NPM package; but that doesn't seem ideal.

**Comment by jaxgeller** [comment]
@jonahbron Sorry but I dont have time to maintain this anymore. Id be open to adding you as a maintainer so you can push to npm on this package's behalf. if thats something you'd be interested in please let me know.

Sorry about the late response everyone, I apologize.

**Comment by jonahbron** [comment]
@jaxgeller I totally understand.  Yes, adding me as a maintainer would be great, thank you 😃

**Comment by jonahbron** [comment]
@jaxgeller I'm still interested in assuming a maintainer role.  My NPM username is `jonahbron` if you can get a moment to add me.

**Comment by jaxgeller** [comment]
@jonahbron sorry for the delay, done! Added as collaborator on github and npm

**Comment by jonahbron** [comment]
@jaxgeller Thank you!  I'll take good care of it for you 😄

**Pull request merged**
